




####################### IMAGING LINEAR MODELS ##############################

    #These functions obtain all LM results, and plots

    #1. lm_creator & lm_table_output:
    #   Obtain the linear models for the phenotype variables of interest & 
    #   print csv tables of these results.
    #2. plot_lm:
    #   Generates brain plot object on the basis of the data generated by the 
    #   first function. Note that you'd have to specify which output variable is
    #   being plotted. 
    #3. plt_aes:
    #   Adds preferred aesthetics to the plots above.
    #4. plt_brain_wrapper:
    #   Wraps around the functions above to generate brain plots for all variables
    #   used in the study generated by the first functiono.
    #5. plt_scatt_lm:
    #   Generates scatterplots for the the ROIs (of a given variable) with the
    #   strongest effects.
    #6. corrplot.simple:
    #   Generates correlations between the beta values of an LM model. 
    #7. lm_360_figures:
    #   Generates supp figures on L/R hemisphere correlation in phe-vars effects


############ Obtain LM results (old fashion) & ggseg prep #################################
#FUNCTION: Gives you linear models between ROIs and CM, AT, BMI, CRP +
#make the df ggseg friendly (note that the CM results are not analyzed)

#NOTE: ggseg friendly edits missing for 360

lm_creator <- function(df.brain, roi_n = NULL, save = F, script_ID = NULL, lateral = F) {
  
  #0.Specifics depending the input data (180 or 360)
  if (roi_n == 180) {
    roi_list<- read_csv(paste0(scriptdir,"0-aux-files/BRAIN_ROIS_187.csv")) %>% pull()
    NROI<-length(roi_list)
    }
  if (roi_n == 360) {NROI<-374 }
  if (roi_n != 360 & roi_n != 180) {NROI<- roi_n}#new
  
  
  #1. Create output placeholder
  LM<- data.frame(matrix(ncol = 6, nrow = 1)) 
  names(LM)<- c('beta', 'std.error', "t.statistic",'pvalue', 
                "BRAIN_ROI", "variable")
  
  #variables to loop through
  vars<- c("CRP", "BMI", "AT", "CM")
  
  #2. Run the models
  for (i in 1:NROI) {
    #current region
    name_current<- roi_list[i]
    
    #Single line placeholder
    pl<- data.frame(matrix(ncol = 6, nrow = length(vars)))
    names(pl)<- c('beta', 'std.error', "t.statistic",'pvalue', 
                  "BRAIN_ROI", "variable")
    
    
    
    #Another loop
    for (x in 1:length(vars)) {
      #Compute linear model for current variable
      pl[x, c('beta', 'std.error', "t.statistic",'pvalue')] <- 
        broom::tidy(lm( data = df.brain, scale(df.brain[,name_current])~
                          scale(df.brain[,vars[x]]),
                        na.action = "na.exclude") )[2,2:5]
      pl[x, "variable"]<- vars[x]
      pl[x, "BRAIN_ROI"] <- name_current
      
    }
    #Append to placeholder
    LM<- bind_rows(LM, pl)
    #print(i)
    rm(pl, x, name_current)
  }
  
  LM<- LM %>% slice(-1)
  LM<- as_tibble(LM)
  
  
  #3. Universal FDR correction by ROI
  LM<- LM %>%
    ungroup() %>%
    group_by(variable) %>%
    mutate(pvalue.FDR = p.adjust(pvalue, method = "fdr")) %>%
    ungroup()
  
  
  ################################ Make 180 df ggseg friendly! ################## 
  #i.e. if we average across both hemispheres
   if (lateral == T){
    LM<- 
      LM %>%
      
      #1.code for cerebral layer:
      mutate(layer = 
               case_when(
                 stringr::str_detect(BRAIN_ROI, "_ROI") == T ~ "ctx",
                 T == T ~ "sub" ))  %>% 
      
      
      #2. code hemisphere and reorganize 
      mutate(hemisphere = "right") %>% 
      
      
      #3. make a label column for ggplot:
      mutate(label = BRAIN_ROI) %>%
      
      #5. eliminate regions not recognized by ggplot (in theory)
      mutate(ggout = case_when( 
        label == "Accumbens-area" ~ T,
        T ~ F)) %>%
      
      #6. reorganize
      relocate("BRAIN_ROI", "layer", "hemisphere", "label") %>%
      
      #7. BMU-brain maps edit
      rename("label_conventional" = "label") %>%
      mutate(across(label_conventional, ~case_when(
        layer == "ctx" ~ str_replace(., "_ROI", ""),
        TRUE ~ .
      ))) %>% 
      
      mutate(across(label_conventional, ~case_when(
        layer == "sub"  ~str_c("Right-",.),
        layer == "ctx"  ~str_c("rh_R_",.)
        
      ))) %>% 
      mutate(across(label_conventional, as.factor))
    
    
  }
  
  
  ################################ Final outputs ################################ 
  #SAVE IF REQUESTED
  if (save == T) {
    write_csv(LM, paste0(scriptdir, "1-model_outputs/data_frames/", script_ID, "_",
                         as.character(roi_n), "_LM_Models.csv" ) )  }
  
  
  
  #Return output
  return(LM)
  
}

#Write a csv file with the full outputs per variable of interest.
lm_table_output<- function(LM_input, script_ID = NULL){
  
  LM_input %>% 
    select(BRAIN_ROI, layer, beta, std.error, t.statistic,
           pvalue, pvalue.FDR, variable)  %>%
    
    #------2. Variable edits
    mutate(across(BRAIN_ROI, ~case_when(
      layer == "ctx" ~ str_replace(., "_ROI", ""),
      TRUE ~ .
    ))) %>% 
    mutate_at(vars(BRAIN_ROI), ~case_when(
      BRAIN_ROI == "Thalamus-Proper" ~ "Thalamus",
      BRAIN_ROI ==  "Accumbens-area" ~ "Accumbens",
      TRUE ~ .
    )) %>% 
    
    
    #3.-------- Column names
    rename(
      "Brain area" = "BRAIN_ROI",
      "SE" = "std.error",
      "t-value" = "t.statistic",
      "p-value" = "pvalue",
      "p-value (FDR corrected)" = "pvalue.FDR"
    ) -> a
  
  for (var in c("BMI", "AT", "CRP")) {
    
    a %>% filter(variable == var) %>%
      select(-variable) %>% 
      write_csv(., paste0(scriptdir, "1-model_outputs/supplement/", 
                          script_ID, "_", var, "_LMtable.csv"))
  }
  
}


################# BRAIN-1. Generate brain plot ###############################################


plot_lm<- function(df, var, filling, threshold = NULL) {
  
  
  #filling: can be either "beta" or "t.statistic" - note that you don't need 
  # to use "" to pass these variable names. 
  
  #----------- Packages
  require(ggseg)
  require(ggsegGlasser)
  require(ggplot2)
  
  
  #------------INPUT BMU BRAIN MAP
  #1. Input variables allowing merger with custom gglasser atlas 
  lab.merge<- 
    read_csv(paste0(scriptdir, "0-aux-files/glasser_sub/glassersub_BRAINROI_merge.csv"))
  
  #2. The following needs to be read outside the function
  load(paste0(scriptdir, "0-aux-files/glasser_sub/glassersub_ggseg155_R.bin"),
       envir = globalenv())
  glassersub$type<<- 'cortical'
  #glassersub$type<- 'cortical'
  
  
  #--------- Thresholding
  df<- df %>%  mutate(plot_fill = {{filling}}) 
  
  if ( threshold == T ) {
    df<-
      df %>% 
      mutate(across(plot_fill, 
                    ~if_else(pvalue.FDR <0.05, plot_fill, NA_real_)))
  }
  
  
  
  #------------INPUT BMU BRAIN MAP + generate baseline plot
  plot<- 
    df %>% left_join(., lab.merge) %>% #merge by BRAIN_ROI!
    rename("label" = "label_BMU") %>%
    filter( ggout == F) %>% 
    filter(variable == var) %>% #Here you do need to match a string
    ggseg(., atlas= 'glassersub', 
          mapping=aes(fill = plot_fill),
          color = "gray3", size =0.3,
          hemisphere = "right", 
          position='stacked') 
  
  
  return(plot)
  
  
}


################ BRAIN-2. Generate aesthetics to add  (brain) ################################

plt_aes<- function(dfo, var, filling, fill_name = NULL) {
  
  #variable: string character indicating whose easthetics are being
  # edited: either CM, CRP, AT, BMI. 
  
  #var: expected as character
  #filling: expected as object (i.e. not as string)
  
  
  #1.----------------- Define legend limits
  var_limits<- dfo %>% 
    group_by(variable) %>%
    mutate(lim_lower = min({{filling}}))%>% 
    mutate(lim_upper = max({{filling}})) %>%
    #store this beautiful thing
    rowwise() %>%
    #keep only the max
    mutate(limit_value = pmax(abs(lim_lower), abs(lim_upper)))  %>%
    #round
    mutate(across( limit_value, ~ signif(.,2))) %>%
    select(variable, limit_value) %>%
    ungroup() %>%
    slice_head(n=4) 
  
  limval<- var_limits$limit_value[var_limits$variable == var]
  
  
  #2.----------------- Define plot title
  titl<- as.character(var_limits$variable[var_limits$variable == var])
  
  # 3.-----------------  Define fill name
  if (fill_name == "t") {fill_name<- "t" }
  
  
  if ( fill_name == "b" ) { fill_name <- "beta" }
  
  #4.-----------------  COLOR PALLETE
  fake_scico <- RColorBrewer::brewer.pal(n = 9, name = "RdBu")
  
  
  #--------------------------- List of easthetic elements to add:
  ggproto<- list(
    scale_fill_gradientn(colors = c(low=fake_scico[1], 
                                    mid=fake_scico[5], 
                                    high=fake_scico[9]),
                         na.value = "transparent",
                         limits = c(-limval, limval),
                         breaks = c(-limval, limval),
                         oob= scales::squish),
    
    
    
    theme_void(),
    theme(
      legend.position="bottom",
      legend.key.height = unit(rel(0.5), "line"),
      legend.key.width =   unit(rel(4), "line"), #3
      legend.text = element_text(size = rel(4)),
      legend.title = element_text(hjust = 0.5, size = rel(4)),
      plot.title = element_text(hjust = 0, size = rel(4), 
                                color = "black",
                                face = "bold")
      
    ),
    guides(fill=guide_colourbar(title.position="top"),
           title.hjust =0.5),
    labs(title = rlang::parse_expr(titl)),
    labs(fill = rlang::parse_expr(fill_name))
    
  )
  
}

################ BRAIN-3 Generate all brain plots for data ###################################

plt_brain_wrapper <- function(LM, script_ID= NULL) {
  
  
  #--------------------0 Plot directories
  #Create directories to store plots and give their addresses
  
  dir_t<- paste0(scriptdir, "3-plots/P4/", script_ID, "/","t_values")
  dir_beta<- paste0(scriptdir, "3-plots/P4/", script_ID, "/","betas")
  dir.create(dir_t, recursive = T)
  dir.create(dir_beta, recursive = T)
  
  #--------------------1.Wrapping function
  #Function for thresholded and unthresholded plots put together,
  #with the aes settings and saved.
  plt_brain_thresholds<- function(LM, x, filling, fill_name){
    
    p_thresh<- plot_lm(LM, x, {{filling}}, threshold = T) +
      plt_aes(LM, x, {{filling}}, fill_name = fill_name)
    
    p_unthresh<- plot_lm(LM, x, {{filling}}, threshold = F) +
      plt_aes(LM, x, {{filling}}, fill_name = fill_name)
    
    
    if(fill_name == "b"){dir.here<-dir_beta}
    if(fill_name == "t"){dir.here<-dir_t}
    
    #----save plots 
    #THRESHOLDED
    ggsave(paste0(dir.here,"/", "THRESH_", x, "_", fill_name, ".png"), p_thresh)
    #UNTRHESHOLDED
    ggsave(paste0(dir.here, "/", "UNtrh_", x, "_", fill_name, ".png"), p_unthresh)
    
    
  }
  
  
  #---------------------2. Wrapper execution 
  single_vars<- c("AT", "BMI", "CRP")
  for(x in single_vars){
    plt_brain_thresholds(LM, x, beta, fill_name = "b")
    plt_brain_thresholds(LM, x, t.statistic, fill_name = "t")
  }
  
  
  
}


################################### PLT: Top ROI scatterplots #################################
#This function will only run after you have run the linear models and stored their output
#for your data of interest. Thus, the only input necessary is the data ID (i.e. "script_ID" or 
# "ID_var" in previous analysis pipelines)

#FUNCTION: for a give linear model of e.g. CT/VOL~CRP it gives you the scatterplot
#of the correlation between these two values for the region where the model has 
#its strongest effect either in the cortex or in the subcortex.

#This function contains some hardcoded parts


plt_scatt_lm <- function(brain, script_ID = NULL) {
  
  
  
  #---------------0. Read in linear model results -------------------------
  LM<- read_csv(paste0(scriptdir, "1-model_outputs/data_frames/", 
                       script_ID, "_180_LM_Models.csv"))
  
  
  #---------------1. Add additional data on the regions  ------------------
  map<- read_csv(paste0(scriptdir, "0-aux-files/" , "glasser_mapping_sofia.csv"))
  map<- map %>% select(BRAIN_ROI, "glasser_region_grouping")
  LM<- LM %>%
    #left_join(., map, by="BRAIN_ROI", na_matched = "NA") %>%
    left_join(., map, by="BRAIN_ROI") %>%
    mutate_at(vars(glasser_region_grouping), ~as.factor(.))
  
  
  #---------------2. Find top (unsigned) cortical & subcortical values ----
  ctx.scatter<-
    LM %>% filter(layer == "ctx" & pvalue.FDR < 0.05  & variable != "CM") %>% 
    group_by(variable) %>%
    filter(abs(t.statistic) == max(abs(t.statistic))) %>% 
    select(variable, BRAIN_ROI, glasser_region_grouping, t.statistic, beta) %>%
    mutate(ROI_name = 
             case_when(str_detect(BRAIN_ROI,"_ROI") == T ~ 
                         str_replace(BRAIN_ROI, "_ROI", ""),
                       TRUE ~ BRAIN_ROI))
  
  sub.scatter<-
    LM %>% filter(layer == "sub" & pvalue.FDR < 0.05  & variable != "CM") %>% 
    group_by(variable) %>%
    filter(abs(t.statistic) == max(abs(t.statistic))) %>% 
    select(variable, BRAIN_ROI,  t.statistic, beta) %>%
    mutate(ROI_name = BRAIN_ROI)
  
  
  #---------------3. Make custom arrangements for plots ----------------
  #Bind
  ctx.scatter$layer<-"ctx"
  sub.scatter$layer<- "sub"   
  scatt <- ctx.scatter %>% bind_rows(sub.scatter)
  
  
  scatt<- 
    #Personalize glasser ROIs
    scatt %>%
    mutate(glasser_me = case_when(
      glasser_region_grouping == "dorsolateral_prefrontal_cortex" ~ "dlPFC",
      glasser_region_grouping == "premotor_cortex" ~ "premotor ctx"
    )) %>%
    
    #color by signage
    mutate(color_dots =case_when(
      t.statistic <0 ~ "brown2" ,
      t.statistic >0 ~ "deepskyblue2"
      
    )) %>%
    ungroup()
  
  
  
  
  
  #----------------------3. Import data on top regions only ---------------
  rois_toimport<- scatt %>% pull(BRAIN_ROI)
  rois_toimport<- c(rois_toimport, "AT", "BMI", "CRP", "eid")
  
  #A. Define df to pull from
  dir<- brain
  
  #B. Input only variables and top regions for scatterplots
  brain_select<- 
    brain %>% select(matches(rois_toimport))
    #data.table::fread(dir, select = unique(rois_toimport)) %>% as_tibble()
  
  
  #----------------------4. Set plot aesthetics ------------------------
  lettering_theme<- theme(text=element_text(size=40,family="sans"), 
                          axis.text=element_text(size=38), 
                          legend.position = "none", #suppress legend of density plot
                          panel.background = element_rect(fill = "white"),
                          title = element_text(size=45),
                          axis.title = element_text(size=45)) 
  
  pubr_regular<- ggpubr::stat_cor(method="spearman", aes(label = ..r.label..),
                                  label.sep = "\n",  size = 18, color = "black") 
  
  
  
  #----------------------5. Loop to create scatterplots -----------------
  
  #A. Set directory for storing the plots
  base.dir<- paste0(scriptdir, "3-plots/P4/", script_ID, "/", "LM_scatters")
  dir.create(base.dir)
  
  #B. Create a sub and ctx scatterplot of variable vs grey matter of the ROI with
  #the largest abs(t.value).
  for (x in 1:length(scatt$variable))  {
    
    temp<- scatt %>% slice(x)
    
    if (temp$layer == "ctx") {
      yylab<- (expression(CT~"("~mm^2~")"))
      ttitl<- paste0("Area ", temp$ROI_name, 
                     " ", "[", temp$glasser_me, "]" )} 
    
    if (temp$layer == "sub") {
      yylab<- (expression(VOL~"("~mm^3~")")) 
      ttitl<- temp$ROI_name} 
    
    ggsave( paste0(base.dir, "/", temp$variable, "_", temp$layer, "_", "ROI_scatt.png"),
            
            ggplot(brain_select, 
                   aes_(x=as.name(temp$variable), y= as.name(temp$BRAIN_ROI)))+
              geom_point(alpha = 0.3, size = 2, shape = 21, fill = "azure4" ) +
              geom_density2d(colour = temp$color_dots, size = 1.5)  +
              geom_smooth(method=lm, colour = "black", size = 2) +
              pubr_regular +
              xlab(temp$variable) +
              ylab(yylab) +
              ggtitle( ttitl) +
              theme_classic()+
              lettering_theme,
            width=9, height=8)
  }
  
}


################################### PLT: Beta correlations #################################

corrplot.simple <- function(df, xvar = "xvar", yvar = "yvar", plotvar = "plotvar") {
  
  #---------------------------A. Aesthetics    
  lettering_theme_corrp<- theme(
                          axis.text=element_text(size=rel(3)), 
                          legend.position = "none", #suppress legend of density plot
                          axis.title = element_text(size = rel(3.5))
                          #title = element_text(size=25))
  )
  
  
  
  #---------------------------B. Conditionals  
  if (plotvar == "t.statistic" ) {
    stat_X<- stringr::str_c("t.statistic_", xvar, sep = "")
    stat_Y<- stringr::str_c("t.statistic_", yvar, sep = "")
    
    varlist<- c("BRAIN_ROI", "layer", "t.statistic", "variable", "pvalue.FDR")
    
    axis_labels<-labs( x = expr(paste(!!xvar, " ",italic("t"))),
                       y = expr(paste(!!yvar, " ",italic("t"))))
    
    
  }
  
  if (plotvar == "beta" ) {
    stat_X<- stringr::str_c("beta_", xvar, sep = "")
    stat_Y<- stringr::str_c("beta_", yvar, sep = "")
    
    varlist<- c("BRAIN_ROI", "layer", "beta", "variable", "pvalue.FDR")
    axis_labels<-labs( x = expr(paste(!!xvar," ",beta)),
                       y = expr(paste(!!yvar, " ", beta)))
    
  }
  
  variableX<- stringr::str_c("pvalue_fdr_", xvar, sep = "")
  variableY<- stringr::str_c("pvalue_fdr_", yvar, sep = "")
  
  
  
  #---------------------------C. Plot
  pplot<- 
    df %>% filter(variable == xvar | variable == yvar) %>%
    filter(layer == "ctx") %>%
    select(all_of(varlist)) %>% 
    tidyr::pivot_wider(names_from = variable, 
                       values_from = c(plotvar, "pvalue.FDR"), names_sep="_")  %>%
    ggplot(., aes_string(x=stat_X, y=stat_Y) )+
    geom_point(size = 3, shape = 21, color = "black", fill = "#00BA38", alpha = 0.5) +
    geom_smooth(method=lm, colour = "black", size = 2, aes(group =1)) +
    ggpubr::stat_cor(method="spearman", aes(label = ..r.label.., group = 1),
                     label.sep = "\n",  size = rel(10), color = "black") +
    theme_classic() +
    lettering_theme_corrp + 
    theme(axis.text=element_text(angle = 45),
                            plot.margin = margin(1,2,1.3,1.3, unit = "cm"),
                            legend.position = "right", aspect.ratio=5/4.5,
                            legend.title = element_blank())  +
    axis_labels
  
  #----------------------------D. Save
  plt_dir<- paste0(scriptdir, "3-plots/P4/", script_ID, "/", 
                   plotvar,  "_CORR_" )
  
  ggsave(paste0(plt_dir, xvar, "_", yvar, ".png"), 
         pplot,  width=11, height=8)
  
}


################################### PLTS & BRAIN: 360 left-right correspondence #################################
#This function only needs to be run for all the plots to be 
#automatically generated. No need to pass it data
 
lm_360_figures <- function(script_ID = NULL) {
  
  #----------------- 1. Generate linear models ------------------------------
  source(paste0(scriptdir, "0_fun_imaging_prep.R"))
  brain<- merger(script_ID, roi_n = 360, save = F)
  
  source(paste0(scriptdir, "4-func_imaging_lms.R"))
  LM3<- lm_creator(brain, roi_n = 360, save=F,
                   script_ID = script_ID, lateral=F)
  
  
  #----------------- 2. Adapt DF for plotting  -------------------------------
  
  LM<- LM3 %>%
    #1. Assign hemisphere
    mutate(hemi = case_when(
      stringr::str_detect(BRAIN_ROI, "^lh") | stringr::str_detect(BRAIN_ROI, "Left") ~ "left",
      stringr::str_detect(BRAIN_ROI, "^rh") | stringr::str_detect(BRAIN_ROI, "Right") ~ "right"
    )) %>% 
    
    #2. Create label
    mutate(label = BRAIN_ROI) %>% 
    mutate(across(label, ~case_when( 
      stringr::str_detect(BRAIN_ROI, "_ROI") ==  T ~ stringr::str_remove(., "_ROI" ),
      T == T ~ .))) %>%
    
    #3. Assign layer
    mutate(layer = case_when(
      stringr::str_detect(BRAIN_ROI, "_ROI") == T ~ "ctx",
      T == T ~ "sub" )) %>%
    relocate(BRAIN_ROI, label, hemi, layer)  %>%
    #4. remove unnused data
    filter(variable != "CM")
  
  
  #----------------- 3. Generate brain plots  ---------------------------------------
  
  dir.here<- paste0(scriptdir, "3-plots/P4/", script_ID, "/", "360_supplement")
  dir.create(dir.here)
  
  #Color settings
  fake_scico <- RColorBrewer::brewer.pal(n = 9, name = "RdBu")
  
  ggsave(paste0(dir.here, "/","subcortex.png"), 
         LM %>% 
           filter(layer == "sub") %>% 
           group_by(variable) %>%
           ggseg(., atlas= aseg, mapping=aes(fill = beta),  view = "axial", 
                 color = "black", size = 0.3)+
           scale_fill_gradient2(low = fake_scico[1], mid=fake_scico[5], high=fake_scico[9],
                                na.value = "transparent")+
           facet_wrap(~variable, ncol= 2, strip.position="left") + 
           labs(fill = expression(beta)) +
           theme_minimal(base_size = 20),  width = 8, height = 6)
  
  ggsave(paste0(dir.here, "/", "cortex.png"), 
         LM %>% 
           filter(layer == "ctx") %>% 
           group_by(variable) %>%
           ggseg(., atlas= glasser, mapping=aes(fill = beta),  color = "black", size = 0.18)+
           scale_fill_gradient2(low = fake_scico[1], mid=fake_scico[5], high=fake_scico[9],
                                na.value = "transparent")+
           facet_wrap(~variable, ncol= 1, strip.position="left") + 
           labs(fill = expression(beta)) +
           theme_minimal(base_size = 18), width = 8, height = 6)
  
  #----------------- 4. Generate scatter-plots  ---------------------------------------
  
  
  
  #1. Create a ROI_ID column that lets you match (by row) left values with
  #right values & pivot_wider
  
  LMp<- 
    LM %>% mutate(roi_id = label) %>% 
    mutate(across(roi_id, ~case_when( 
      stringr::str_detect(roi_id, "^lh") == T ~ stringr::str_replace(., "lh_L_", ""),
      stringr::str_detect(roi_id, "Left") == T ~ stringr::str_replace(., "Left-", ""),
      stringr::str_detect(roi_id, "Right") == T ~ stringr::str_replace(., "Right-", ""),
      stringr::str_detect(roi_id,"^rh") == T ~ stringr::str_replace(., "rh_R_", "")
    ))) %>% 
    select(hemi,layer, variable, beta, roi_id) %>%
    pivot_wider(names_from = c(hemi),
                values_from = c(beta), 
                names_prefix  = "beta_") 
  
  #2. Plot 
  pu.brr<- ggpubr::stat_cor(method="spearman", label.sep = "\n",
                            size = 6, color = "blue", label.y = 0.04)  
  
  ggsave(paste0(dir.here, "/", "L_R_corr_scatterplots.png"),
         LMp %>%  
           ggplot( aes(x=beta_right, y=beta_left))+
           geom_point(alpha = 1,size = 1) +
           geom_smooth(method=lm, colour = "blue")+
           pu.brr +
           facet_wrap(~variable, ncol= 3) +
           xlab(expression(Right~hemisphere~beta))+
           ylab(expression(Left~hemisphere~beta))+
           theme_classic() +
           theme(text=element_text(size=14),
                 axis.text.x = element_text(size = 15, angle = 90),
                 axis.text.y = element_text(size = 20, angle = 0),
                 axis.title = element_text(size = 20)),
         height = 4, width = 8.00
  )
           
 
}




